### ISSUE TITLE
Unable to load EGL library

### ISSUE THREAD

**Issue by harikrik007** [yw0208/W-HMR#7]
I am using window11 , anaconda environment with python 3.8.

utils\renderer_cam.py", line 130, in render_overlay_image
    renderer = pyrender.OffscreenRenderer(

The above line produces an exception 

OpenGL\platform\egl.py", line 86, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)
Installed pyopengl,pyopengl-accelerate

I am able to get pkl file with --no_render param but i need the .obj file
Please help me rectify the issue

**Comment by yw0208** [comment]
OK, you have saved SMPL params in pkl files, then you can get obj files like following codes:
`
smpl->vertices->mesh->obj

    output = smpl_model(body_pose=rotations, global_orient=global_orient, betas=betas)
    vertices = output["vertices"]
    # visualize: vertices to obj
    mesh=Trimesh(vertices=vertices,faces=smpl_model.faces)
    save_path="scratch/temp/mesh_obj/mesh.obj"
    with open(save_path, 'w') as fw:
        mesh.export(fw, 'obj')`

**Comment by harikrik007** [comment]
Thanks for your help.
 1) I have tried out the inference and got the output meshes. It looks cool. The issue that I found was that, visual accuracy and measurement accuracy is lagging for a case of a plus size person. Would like to hear your comments on this to know if I missed anything.
2) Meanwhile I saw your mention about the training codes, would like to see it when it’s ready. 
Best Regards,

**Comment by yw0208** [comment]
> Thanks for your help.
> 
> 1. I have tried out the inference and got the output meshes. It looks cool. The issue that I found was that, visual accuracy and measurement accuracy is lagging for a case of a plus size person. Would like to hear your comments on this to know if I missed anything.
> 2. Meanwhile I saw your mention about the training codes, would like to see it when it’s ready.
>    Best Regards,

Hi, I have noticed your questions, here are my reply.
1. A plus size person? Do  you mean these overweight humans? I think this is mainly due to the lack of training data. Although I have used most of the classic datasets, they are relatively lacking in samples of overweight people. For this kind of overweight people, you can refer to this article _Everybody Is Unique: Towards Unbiased Human Mesh Recovery_. I remember there are other papers that try to solve this problem, but I forget the paper names. You can try google them.
2. I had planned to make all the code public after the paper was published, but it seems that this will take a long time. So I plan to make all the code public next week. However, the code has not been organized, so it may be confusing and have bugs. Please feel free to contact me when the time comes.
